
import type { MediaItem } from './media-types';
import { mediaFL } from './media-fl';
import { mediaB } from './media-b';
import { mediaL } from './media-l';
import { mediaGeral } from './media-geral';

export type { MediaItem };

const INHAME_ARANHA_STORY = `INHAME-ARANHA, INHAME-ARANHA
Na feira orgânica ele encanta
Nutritivo e natural,
Herói do campo, sensacional!

Com grandes fibras, vêm grandes responsabilidades!

Ele era só um tubérculo comum... até ser picado por uma aranha diferentona e cheia de energia, que vivia em um solo superadubado e rico em matéria orgânica de uma fazenda agroecológica! Agora, o Inhame-Aranha salta sobre hortas e prédios, lança teias nutritivas e enfrenta os maiores vilões do planeta: os agrotóxicos!

Rico em vitaminas — principalmente as do complexo B —, fibras, propriedades anti-inflamatórias e desintoxicantes, o Inhame-Aranha não só derrota os inimigos da saúde, como ainda fortalece o sistema imunológico de quem acredita nele. Quando necessário, nosso herói de cara rugosa, mas coração cremoso, coloca sua máscara e luta bravamente contra as corporações que envenenam nossos pratos e adoecem nossa população. Defensor dos orgânicos, guardião das hortaliças e protetor dos pequenos agricultores, o Inhame-Aranha está aqui para te despertar para um mundo mais saudável, sustentável e saboroso.

Prepare-se: a revolução vegetal chegou às alturas! Se você quer saúde de verdade, então vem pras feiras orgânicas nesse sábado e traga sua ecobag! O Inhame-Aranha estará te esperando com sabor, coragem e muitos vegetais do bem!`;

const UVERINE_STORY = `VENHA ENCONTRAR O UVERINE E MUITOS OUTROS HERÓIS DA NATUREZA EM NOSSAS FEIRAS ORGÂNICAS DO CIRCUITIO CARIOCA! 

Com garras de resveramantium, compostas por um alto teor de antioxidantes vindos de seu próprio sangue (ou melhor, do suco), Uverine não é um herói derivado de qualquer uva. Ele é o resultado de uma mutação natural envolvendo as lendárias uvas amarelas Niágara, Itália e Chardonnay — uma fusão poderosa que deu origem ao mais casca-grossa dos heróis orgânicos. Imortal, indestrutível e com um leve aroma frutado, Uverine corta, com suas afiadas garras de resveramantium, as toxinas, os radicais livres e os vilões agrotóxicos que ameaçam sua saúde e a do planeta. Quando Uverine não está em trabalho de podas regenerativas em plantações de videiras, ele está ao lado dos X-Veggies na defesa de uma alimentação limpa, sustentável e deliciosa, protegendo hortas, lavouras e a dignidade das famílias agricultoras. Uverine não envelhece — e luta todos os dias para que você também se torne longevo, viva melhor e mais protegido. Ele pode até guardar alguma doçura interior, mas, quando abre os braços e aciona suas garras… já era!

A batalha pela saúde começa no seu prato e Uverine já escolheu o lado certo da luta. E você? Venha fortalecer-se nas feiras Orgânicas do Circuito Carioca!`;


export const allMedia: MediaItem[] = [
  // Mídias de Flamengo e Laranjeiras agora são importadas
  ...mediaFL,
  // Mídias de Botafogo agora são importadas
  ...mediaB,
  // Mídias do Leme agora são importadas
  ...mediaL,
  // Mídias gerais para todas as feiras (exceto Fla/Laranjeiras)
  ...mediaGeral,
  
  // Mídias existentes de outras feiras
  { id: "tijuca-1", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_84_feira_tijuca.png?alt=media&token=b917b926-b18e-47a0-8a7e-5b7f5f330ca9", alt: "fot_84_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-2", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_76_abobrinha_maravilha.png?alt=media&token=91fe35d1-61d0-4c47-aab4-be6a0cd06f30", alt: "ap_cartoon_feira_tijuca_76_abobrinha_maravilha", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-3", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_92_beterraba_de_ferro.png?alt=media&token=8082d54a-1cde-4893-9b5d-ec123e3f84f3", alt: "ap_cartoon_feira_tijuca_92_beterraba_de_ferro", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-4", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_81_pepino_verde.png?alt=media&token=b33cf144-855e-4731-aaf6-3de935f12bf8", alt: "ap_cartoon_feira_tijuca_81_pepino_verde", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-5", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_48_batatman.mp4?alt=media&token=b294d6aa-3bc5-444e-9887-602c546b901b", alt: "ap_feira_tijuca_48_batatman", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-6", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_49_inhame_aranha.mp4?alt=media&token=806d4f89-478f-447f-a1b9-f56a11c70adb", alt: "ap_feira_tijuca_49_inhame_aranha", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens", characterName: "Inhame-Aranha", story: INHAME_ARANHA_STORY },
  { id: "tijuca-7", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_52_robinete.mp4?alt=media&token=d22a3e62-056e-4e0e-ac0a-a1d484f4093a", alt: "ap_feira_tijuca_52_robinete", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-8", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_54_sporock.mp4?alt=media&token=3d4055cf-76d2-45e4-a62a-a1c553b78ca8", alt: "ap_feira_tijuca_54_sporock", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-9", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_57_aqualface.mp4?alt=media&token=e41f3c31-8497-401f-8fe2-982ed1077501", alt: "ap_feira_tijuca_57_aqualface", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-10", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_61_uva_negra.mp4?alt=media&token=c03748c9-20b7-45d2-a481-91da4ad879a1", alt: "ap_feira_tijuca_61_uva_negra", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-11", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_63_coisa_de_milho.mp4?alt=media&token=5df59f3d-73b8-4329-b28a-c0aabd7a38b5", alt: "ap_feira_tijuca_63_coisa_de_milho", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-12", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_66_limao_america.mp4?alt=media&token=4db398b0-b3d6-4ea1-80de-b64bf18aeac9", alt: "ap_feira_tijuca_66_limao_america", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-13", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_68_uverine.mp4?alt=media&token=5a60387d-2326-4e17-a5ff-e4bd45602f02", alt: "ap_feira_tijuca_68_uverine", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens", characterName: "Uverine", story: UVERINE_STORY },
  { id: "tijuca-14", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_69_berinjela_negra.mp4?alt=media&token=bcdf44e0-5bc5-4646-9379-caf271254a04", alt: "ap_feira_tijuca_69_berinjela_negra", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-15", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_71_brulk.mp4?alt=media&token=ab21e3a9-38d5-4d5a-82d0-d5f51839e53c", alt: "ap_feira_tijuca_71_brulk", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-16", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_74_mandiorpheus.mp4?alt=media&token=929cebd8-b86a-4bc1-b866-9b995315d36f", alt: "ap_feira_tijuca_74_mandiorpheus", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-17", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_75_abobrinha_maravilha.mp4?alt=media&token=00645545-1ab5-43af-91c9-150f884b1519", alt: "ap_feira_tijuca_75_abobrinha_maravilha", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-18", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_80_pepino_verde.mp4?alt=media&token=a2e427e8-7c74-4957-8fe7-32898c98057d", alt: "ap_feira_tijuca_80_pepino_verde", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-19", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_91_beterraba_de_ferro.mp4?alt=media&token=79cfaddf-d0c0-48fb-9480-0787d66ac5d9", alt: "ap_feira_tijuca_91_beterraba_de_ferro", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-20", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_19_feira_tijuca.png?alt=media&token=4e260f86-df2f-48ce-b2b7-fb4392238c78", alt: "fot_19_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-21", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_20_feira_tijuca.png?alt=media&token=03b7cf6a-1a44-4ce7-8124-a226d015e744", alt: "fot_20_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-22", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_24_feira_tijuca.png?alt=media&token=832130cc-aa17-4c9c-8831-65ce5afa6f7e", alt: "fot_24_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-23", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_26_feira_tijuca.png?alt=media&token=87d284bb-fcb4-45a3-bf78-22df26b61fa2", alt: "fot_26_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-24", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_55_feira_tijuca.png?alt=media&token=30c8642d-e2a0-4430-a7a6-c66a0f12616f", alt: "fot_55_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-25", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_56_feira_tijuca.png?alt=media&token=9f6e3d53-a3cc-4a77-926d-10788562a49b", alt: "fot_56_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-26", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_60_feira_tijuca.png?alt=media&token=8dd9da8a-fbd5-4da9-838a-566628fbfab9", alt: "fot_60_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-27", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_85_feira_tijuca.png?alt=media&token=1ac6fe57-cd40-4eb4-8ef2-976553fb0df8", alt: "fot_85_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-28", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_86_feira_tijuca.png?alt=media&token=763116d2-7de6-4820-9d99-c766ec4b43aa", alt: "fot_86_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-29", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_87_feira_tijuca.png?alt=media&token=61bb8d0a-2fef-4976-bbc2-70feacf5afaa", alt: "fot_87_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-30", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_88_feira_tijuca.png?alt=media&token=34f98bc7-9df9-496b-9906-7832631d7bce", alt: "fot_88_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-31", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_89_feira_tijuca.png?alt=media&token=8271db31-fe68-44a5-b7a2-fffd5099e8d5", alt: "fot_89_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-32", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_90_feira_tijuca.png?alt=media&token=6713f0ea-e6ea-4d4e-baa6-2752c96629a1", alt: "fot_90_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-33", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_93_feira_tijuca.png?alt=media&token=b81cf871-963a-43cc-8d18-37ffadd120cd", alt: "fot_93_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-34", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_94_feira_tijuca.png?alt=media&token=4b6675af-13d8-4bac-b090-d75c0d2e3ad4", alt: "fot_94_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-35", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_95_feira_tijuca.png?alt=media&token=dec2b9e4-c43a-465a-8bc9-1e1814e5ae92", alt: "fot_95_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-36", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_chuva_02_feira_tijuca.png?alt=media&token=13cc260e-0264-4610-8c4d-32b5e45eeee5", alt: "fot_chuva_02_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Dias de Chuva", "data-ai-hint": "rainy market" },
  { id: "tijuca-37", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_chuva_09_feira_tijuca.png?alt=media&token=1a6c1288-cc77-4467-ab2e-1252bd2c524f", alt: "fot_chuva_09_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Dias de Chuva", "data-ai-hint": "rainy market" },
  { id: "tijuca-38", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_34_luciene.mp4?alt=media&token=cdcf9e6d-6bd3-4582-86f3-65ae7d427a74", alt: "aagr_feira_tijuca_34_luciene", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-39", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_01_mel.png?alt=media&token=43166b46-40e1-4a24-a05b-463f0dbc7c53", alt: "ap_cartoon_feira_tijuca_01_mel", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "honey cartoon" },
  { id: "tijuca-40", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_02_mel.png?alt=media&token=d0d1e9f5-7a04-4930-9f43-bbd1ab9475c2", alt: "ap_cartoon_feira_tijuca_02_mel", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "honey cartoon" },
  { id: "tijuca-41", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_03_mel.png?alt=media&token=6f466dd4-b161-4c8e-9d98-7a914d0e0ee4", alt: "ap_cartoon_feira_tijuca_03_mel", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "honey cartoon" },
  { id: "tijuca-42", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_04_mel.png?alt=media&token=93903b54-3291-4894-b8e7-282e304dc98f", alt: "ap_cartoon_feira_tijuca_04_mel", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "honey cartoon" },
  { id: "tijuca-43", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_02_mel.mp4?alt=media&token=016feb00-29b0-423b-ba48-6f84892ec844", alt: "ap_feira_tijuca_02_mel", author: "Essência Vital", fair: "Tijuca", style: "Animações de Personagens" },
  { id: "tijuca-44", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_42_lucia.mp4?alt=media&token=7b9c7554-a8ef-47f7-ade2-0242a639efe5", alt: "aagr_feira_tijuca_42_lucia", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-45", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_story_feira_tijuca_02_mel.png?alt=media&token=04fb1ba7-06c8-4dbd-86ff-acb8afcddefb", alt: "ap_cartoon_story_feira_tijuca_02_mel", author: "Essência Vital", fair: "Tijuca", style: "Story", "data-ai-hint": "honey story" },
  { id: "tijuca-46", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_96_feira_tijuca.png?alt=media&token=c04cc2eb-3524-41ce-9778-905956e889dd", alt: "fot_96_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-47", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_cartoon_feira_tijuca_39_lucia.png?alt=media&token=fc58054a-ae29-436c-b917-c947b616ece8", alt: "aagr_cartoon_feira_tijuca_39_lucia", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores", "data-ai-hint": "farmer cartoon" },
  { id: "tijuca-48", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_cartoon_feira_tijuca_40_evelyn.png?alt=media&token=9d38b9c4-2927-40d5-a1f5-1a88f63cca77", alt: "aagr_cartoon_feira_tijuca_40_evelyn", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores", "data-ai-hint": "farmer cartoon" },
  { id: "tijuca-49", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_cartoon_feira_tijuca_41_luciene.png?alt=media&token=3f34879d-d22c-4c5f-999a-7502e63bba97", alt: "aagr_cartoon_feira_tijuca_41_luciene", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores", "data-ai-hint": "farmer cartoon" },
  { id: "tijuca-50", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_cartoon_feira_tijuca_44_rosana.png?alt=media&token=2faba5ab-8013-4350-83dd-7eaba75c7a3d", alt: "aagr_cartoon_feira_tijuca_44_rosana", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores", "data-ai-hint": "farmer cartoon" },
  { id: "tijuca-51", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_38a_rosana_evelyn.mp4?alt=media&token=c810b4c3-cfaa-4653-89d9-a761818721fa", alt: "aagr_feira_tijuca_38a_rosana_evelyn", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-52", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_38b_rosana_evelyn.mp4?alt=media&token=be14f67b-fe93-44a2-b52b-86ea155e087d", alt: "aagr_feira_tijuca_38b_rosana_evelyn", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-53", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_42_lucia.mp4?alt=media&token=7b9c7554-a8ef-47f7-ade2-0242a639efe5", alt: "aagr_feira_tijuca_42_lucia", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-54", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_43a_evelyn.mp4?alt=media&token=59369c96-e1ad-4bfd-ace3-8f6076900904", alt: "aagr_feira_tijuca_43a_evelyn", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-55", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_43b_evelyn.mp4?alt=media&token=9a2a17ab-77d9-4391-b936-0fcac0c3223e", alt: "aagr_feira_tijuca_43b_evelyn", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-56", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_45_rosana.mp4?alt=media&token=0c69991f-332f-45c4-9d87-16ade153eed4", alt: "aagr_feira_tijuca_45_rosana", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-57", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faagr_feira_tijuca_47_rosana_evelyn.mp4?alt=media&token=0b9cfc9a-c564-4ca8-b8dd-dc77e9dc5729", alt: "aagr_feira_tijuca_47_rosana_evelyn", author: "Essência Vital", fair: "Tijuca", style: "Animações de Agricultores" },
  { id: "tijuca-58", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_031_abacate_feira_tijuca.mp4?alt=media&token=a10245e4-f097-4d02-904d-ebb007a16cd3", alt: "aali_031_abacate_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos" },
  { id: "tijuca-59", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_032_maracugina_feira_tijuca.mp4?alt=media&token=18df391b-2e53-4dc4-931f-10f4512ed562", alt: "aali_032_maracugina_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos" },
  { id: "tijuca-60", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_078_maca_feira_tijuca.mp4?alt=media&token=61f1e1a5-01cf-4fc1-88ca-e630c5f0b1ba", alt: "aali_078_maca_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos" },
  { id: "tijuca-61", type: "video", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_083_cenoura_feira_tijuca.mp4?alt=media&token=1f51b03b-4729-4f70-ad75-1c81231a16cc", alt: "aali_083_cenoura_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos" },
  { id: "tijuca-62", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_cartoon_025_tomate_feira_tijuca.png?alt=media&token=d8f0fa8f-ad1a-4696-b18a-f4f4cde48f6c", alt: "aali_cartoon_025_tomate_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos", "data-ai-hint": "food cartoon" },
  { id: "tijuca-63", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_cartoon_039_abacate_feira_tijuca.png?alt=media&token=405a28a8-0c72-483a-87bc-a969737b2aa3", alt: "aali_cartoon_039_abacate_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos", "data-ai-hint": "food cartoon" },
  { id: "tijuca-64", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_cartoon_077_maca_feira_tijuca.png?alt=media&token=ff9978c3-8824-406e-8b9f-56ad046cc34c", alt: "aali_cartoon_077_maca_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos", "data-ai-hint": "food cartoon" },
  { id: "tijuca-65", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_cartoon_079_maracugina_feira_tijuca.png?alt=media&token=f7841ee2-91ff-4259-87f6-7d6f99e2aba7", alt: "aali_cartoon_079_maracugina_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos", "data-ai-hint": "food cartoon" },
  { id: "tijuca-66", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Faali_cartoon_082_cenoura_feira_tijuca.png?alt=media&token=7ef0a6d6-37ce-40e0-8654-70eff80a5a5b", alt: "aali_cartoon_082_cenoura_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Animações de Alimentos", "data-ai-hint": "food cartoon" },
  { id: "tijuca-67", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_21_joaninha.png?alt=media&token=752d11e3-ae78-446d-ad76-2c94823fc2a2", alt: "ap_cartoon_feira_tijuca_21_joaninha", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-68", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_50_inhame_aranha.png?alt=media&token=2c0bd11a-08f3-4b29-98ca-1e3ce00e1127", alt: "ap_cartoon_feira_tijuca_50_inhame_aranha", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon", characterName: "Inhame-Aranha", story: INHAME_ARANHA_STORY },
  { id: "tijuca-69", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_51_batatman.png?alt=media&token=d7e06552-4821-4ea1-8469-e2b0979405c8", alt: "ap_cartoon_feira_tijuca_51_batatman", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-70", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_53_robinete.png?alt=media&token=b2bba7a7-b4ac-49ef-94d8-386161459896", alt: "ap_cartoon_feira_tijuca_53_robinete", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-71", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_58_aqualface.png?alt=media&token=57330ade-030e-4e9e-b949-1bcbb91a5c88", alt: "ap_cartoon_feira_tijuca_58_aqualface", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-72", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_59_sporock.png?alt=media&token=2ebffec2-5b53-4d64-9ae1-17065e8f8b34", alt: "ap_cartoon_feira_tijuca_59_sporock", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-73", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_62_uva_negra.png?alt=media&token=e71f5f17-9b97-4faf-9086-b6b10e71f184", alt: "ap_cartoon_feira_tijuca_62_uva_negra", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-74", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_64_coisa_de_milho.png?alt=media&token=ce945b98-3794-4794-9d46-3dcb677d3da8", alt: "ap_cartoon_feira_tijuca_64_coisa_de_milho", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-75", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_65_limao_america.png?alt=media&token=02d43d7a-b3b5-4f20-b473-a4d895ff2bc3", alt: "ap_cartoon_feira_tijuca_65_limao_america", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-76", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_67_uverine.png?alt=media&token=ef1cf006-f941-44b6-bf1e-c7d007854b33", alt: "ap_cartoon_feira_tijuca_67_uverine", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon", characterName: "Uverine", story: UVERINE_STORY },
  { id: "tijuca-77", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_70_berinjela_negra.png?alt=media&token=eedd470f-fad7-46b3-a078-33aeea795cf8", alt: "ap_cartoon_feira_tijuca_70_berinjela_negra", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-78", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_72_brulk.png?alt=media&token=fd3cc972-f2da-47c0-adec-d5caeb0b90f3", alt: "ap_cartoon_feira_tijuca_72_brulk", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: "tijuca-79", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_73_mandiorpheus.png?alt=media&token=aaea14d0-93b9-4e02-93ae-0e6e60d4da6d", alt: "ap_cartoon_feira_tijuca_73_mandiorpheus", author: "Essência Vital", fair: "Tijuca", style: "Cartoon", "data-ai-hint": "character cartoon" },
  { id: 'grajau-65', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_79_feira_grajau.png?alt=media&token=38991fd5-31d8-488d-9314-5b7e11c86cf4', type: 'image', alt: 'fot_79_feira_grajau', author: 'Essência Vital', fair: 'Grajaú', style: 'Fotografia' },
  { id: 'grajau-66', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_80_feira_grajau.png?alt=media&token=14399f5a-ebdf-411c-8c48-bd23058446d9', type: 'image', alt: 'fot_80_feira_grajau', author: 'Essência Vital', fair: 'Grajaú', style: 'Fotografia' },
  { id: 'tijuca-80', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_97_feira_tijuca.png?alt=media&token=0fc79951-0da0-4575-ae62-4220be582aa8', type: 'image', alt: 'fot_97_feira_tijuca', author: 'Essência Vital', fair: 'Tijuca', style: 'Fotografia' },
  { id: 'tijuca-81', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_98_feira_tijuca.png?alt=media&token=4ddc1ed9-63a7-4f47-9746-08ccdc1ac6b0', type: 'image', alt: 'fot_98_feira_tijuca', author: 'Essência Vital', fair: 'Tijuca', style: 'Fotografia' },
  { id: "tijuca-82", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_108_feira_tijuca.png?alt=media&token=1d4a0ad6-771c-4980-983d-b2dba4ed00c5", alt: "fot_108_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-83", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_109_feira_tijuca.png?alt=media&token=2608865d-c8f5-446d-853d-e076be396703", alt: "fot_109_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-84", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_105_feira_tijuca.png?alt=media&token=3b289e7a-d954-47b3-942d-8f050dfcdce8", alt: "fot_105_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-85", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_106_feira_tijuca.png?alt=media&token=78b040f6-5313-43a4-a2e9-9e4ead9daf91", alt: "fot_106_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: "tijuca-86", type: "image", src: "https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Ffot_107_feira_tijuca.png?alt=media&token=1993f58e-72d7-462e-bf76-3bc92f7fe101", alt: "fot_107_feira_tijuca", author: "Essência Vital", fair: "Tijuca", style: "Fotografia", "data-ai-hint": "market photo" },
  { id: 'tijuca-87', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_100_deadpepper.jpg?alt=media&token=dd0e0557-b1e1-45b1-8afa-bc1b7890e18b', type: 'image', alt: 'ap_cartoon_feira_tijuca_100_deadpepper.jpg', author: 'Essência Vital', fair: 'Tijuca', style: 'Cartoon' },
  { id: 'tijuca-88', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_99_deadpepper.mp4?alt=media&token=f676541f-ad7d-46b0-ae9a-ce7e43605426', type: 'video', alt: 'ap_feira_tijuca_99_deadpepper.mp4', author: 'Essência Vital', fair: 'Tijuca', style: 'Animações de Personagens' },
  { id: 'grajau-67', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_grajau_81_deadpepper.mp4?alt=media&token=67f0ecee-08a8-4fff-a0d9-8b1d31dd9438', type: 'video', alt: 'ap_feira_grajau_81_deadpepper.mp4', author: 'Essência Vital', fair: 'Grajaú', style: 'Animações de Personagens' },
  { id: 'grajau-68', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_grajau_82_deadpepper.jpg?alt=media&token=d1a9edbe-7abd-4cd7-bc3f-fda1bb32bb82', type: 'image', alt: 'ap_cartoon_feira_grajau_82_deadpepper.jpg', author: 'Essência Vital', fair: 'Grajaú', style: 'Cartoon' },
  { id: 'tijuca-89', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_102_thalhor.mp4?alt=media&token=a4952c6a-1967-46ba-a21a-7a20b445d141', type: 'video', alt: 'ap_feira_tijuca_102_thalhor.mp4', author: 'Essência Vital', fair: 'Tijuca', style: 'Animações de Personagens' },
  { id: 'grajau-69', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_grajau_84_thalhor.mp4?alt=media&token=db3d1d29-1474-4adb-b517-ae9a7e0719ca', type: 'video', alt: 'ap_feira_grajau_84_thalhor.mp4', author: 'Essência Vital', fair: 'Grajaú', style: 'Animações de Personagens' },
  { id: 'tijuca-90', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_101_thalhor.png?alt=media&token=d428168b-59b4-4599-8225-456faa9e2c1e', type: 'image', alt: 'ap_cartoon_feira_tijuca_101_thalhor.png', author: 'Essência Vital', fair: 'Tijuca', style: 'Cartoon' },
  { id: 'grajau-70', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_grajau_83_thalhor.png?alt=media&token=cd24decc-3505-4a05-86e8-4b00b920c0b0', type: 'image', alt: 'ap_cartoon_feira_grajau_83_thalhor.png', author: 'Essência Vital', fair: 'Grajaú', style: 'Cartoon' },
  { id: 'tijuca-91', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_tijuca_104_drshiitaker.mp4?alt=media&token=3632cded-6d51-4b11-a55c-40a37c05cfd2', type: 'video', alt: 'ap_feira_tijuca_104_drshiitaker.mp4', author: 'Essência Vital', fair: 'Tijuca', style: 'Animações de Personagens' },
  { id: 'grajau-71', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_feira_grajau_86_drshiitaker.mp4?alt=media&token=8eccbe82-8875-4598-832a-2dbbdd844d44', type: 'video', alt: 'ap_feira_grajau_86_drshiitaker.mp4', author: 'Essência Vital', fair: 'Grajaú', style: 'Animações de Personagens' },
  { id: 'grajau-72', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_grajau_85_drshiitaker.png?alt=media&token=efab6150-3778-43ff-9666-4dce58b98fc4', type: 'image', alt: 'ap_cartoon_feira_grajau_85_drshiitaker.png', author: 'Essência Vital', fair: 'Grajaú', style: 'Cartoon' },
  { id: 'tijuca-92', src: 'https://firebasestorage.googleapis.com/v0/b/verdant-market-x1qp8.firebasestorage.app/o/media_minha_feira%2Fap_cartoon_feira_tijuca_103_drshiitaker.png?alt=media&token=56878ecd-7fce-4b80-aedb-1ce8b60e32ef', type: 'image', alt: 'ap_cartoon_feira_tijuca_103_drshiitaker.png', author: 'Essência Vital', fair: 'Tijuca', style: 'Cartoon' }
]

export const fairs = [...new Set(allMedia.map((item) => item.fair))].sort((a, b) => a.localeCompare(b));
export const styles = [...new Set(allMedia.map((item) => item.style))].sort((a, b) => a.localeCompare(b));

    

    

    
